[variables]
  NIXPACKS_NODEJS_VERSION = "22"

[phases.build]
  commands = [
    "npm install --legacy-peer-deps",
    "npx prisma generate",
    "npx prisma migrate deploy",
    "npm run build"
  ]

[phases.install]
  packages = ["nodejs-22_x", "npm-10_x"]
